name: coding_challange
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

assets:
  - assets/images/png/
  - assets/images/svg/
